#ifndef ADC_PRIVATE_H
#define ADC_PRIVATE_H

#define CLEAR_REFERENCE_SELECTION 0b00111111
#define CLEAR_SFIOR 0b00011111
#define RIGHT 25
#define LEFT 26
#define CLEAR 0b11100000
#define CLEAR_SCALAR 0b11111000
#define BIT_8 8
#define BIT_10 10
#define AREF 0
#define AVCC 64
#define INTERNAL 192
#define ENABLE_AUTO_TRIGGER 1
#define DISABLE_AUTO_TRIGGER 2
#define NONE 0
#define SINGLE_CHANNEL_ASYNC 1
#define CHAIN_ASYNC 2

enum CHANNEL
{
  ADC0,
  ADC1,
  ADC2,
  ADC3,
  ADC4,
  ADC5,
  ADC6,
  ADC7
} CHANNEL;

enum AUTO_TRIGGER_SOURCE
{
  FREE_RUNNING_MODE,
  ANALOG_COMPARATOR,
  EXTERNAL_INTERRUPT_REQUEST_0,
  TIMER_COUNTER_0_COMPARE_MATCH,
  TIMER_COUNTER_0_OVERFLOW,
  TIMER_COUNTER_COMPARE_MATCH_B,
  TIMER_COUNTER_1_OVERFLOW,
  TIMER_COUNTER_1_CAPTURE_EVENT
} AUTO_TRIGGER_SOURCE;

enum DIVFACTOR_ADC
{
  PRE_SCALAR_VALUE_2 = 1,
  PRE_SCALAR_VALUE_4,
  PRE_SCALAR_VALUE_8,
  PRE_SCALAR_VALUE_16,
  PRE_SCALAR_VALUE_32,
  PRE_SCALAR_VALUE_64,
  PRE_SCALAR_VALUE_128
} DIVFACTOR_ADC;

#define ADMUX *((volatile u8 *)0x27)
#define ADMUX_ADLAR 5
#define ADMUX_REFS0 6
#define ADMUX_REFS1 7

#define ADCSRA *((volatile u8 *)0x26)
#define ADCSRA_ADEN 7
#define ADCSRA_ADSC 6
#define ADCSRA_ADATE 5
#define ADCSRA_ADIF 4
#define ADCSRA_ADIE 3
#define ADCSRA_ADPS2 2
#define ADCSRA_ADPS1 1
#define ADCSRA_ADPS0 0

#define SFIOR *((volatile u8 *)0x50)
#define SFIOR_ADTS0 5
#define SFIOR_ADTS1 6
#define SFIOR_ADTS2 7

#define ADCL *((volatile u16 *)0x24)
#define ADCH *((volatile u8 *)0x25)

#endif
