#ifndef TIMER_CONFIG_H
#define TIMER_CONFIG_H

/*

TIMER_0_MODES:

For Normal Mode --> TIMER_0_NORMAL_MODE_SET
For PHASE_CORRECT Mode --> TIMER_0_PWM_PHASE_CORRECT_MODE_SET
For CTC Mode --> TIMER_0_CTC_MODE_SET
For FAST_PWM Mode --> TIMER_0_FAST_PWM_MODE_SET

*/
#define TIMER_0_MODE TIMER_0_NORMAL_MODE_SET

/* Set Timer_0 Compare Match Value */
#define TIMER_0_COMPARE_MATCH_VALUE 0

/* Set Timer_0 PreLoad Value */
#define TIMER_0_PRELOAD_VALUE 0

/*
ENABLE_TIMER_0_COMPAREMATCH_INTERRUPT
DISABLE_TIMER_0_COMPAREMATCH_INTERRUPT
*/
#define TIMER_0_COMPAREMATCH_INTERRUPT_STATUS DISABLE_TIMER_0_COMPAREMATCH_INTERRUPT

/*
ENABLE_TIMER_0_OVERFLOW_INTERRUPT
DISABLE_TIMER_0_OVERFLOW_INTERRUPT
*/
#define TIMER_0_OVERFLOW_INTERRUPT_STATUS ENABLE_TIMER_0_OVERFLOW_INTERRUPT

/*
TIMER_0_PRE_SCALAR_VALUE:

    PRE_SCALAR_VALUE_NO_CLOCK,
    PRE_SCALAR_VALUE_NONE,
    PRE_SCALAR_VALUE_8,
    PRE_SCALAR_VALUE_64,
    PRE_SCALAR_VALUE_256,
    PRE_SCALAR_VALUE_1024,
    EXTERNAL_CLOCK_ON_T_BIN_FALLINGEDGE,
    EXTERNAL_CLOCK_ON_T_BIN_RISINGEDGE

*/
#define TIMER_0_PRE_SCALAR_VALUE PRE_SCALAR_VALUE_1024

/*
Non_PWM Modes (CTC,NORMAL):

    OC0_DISCONNECTED_NONPWM
    TOGGLE_OC0_ON_COMPARE
    CLEAR_OC0_ON_COMPARE
    SET_OC0_ON_COMPARE
*/
#define TIMER_0_NON_PWM_COMPARE_OUTPUT_MODE OC0_DISCONNECTED_NONPWM

/*
FAST_PWM Mode:

    OC0_DISCONNECTED_FPWM
    RESERVED_TIMER0_FPWM
    CLEAR_OC0_ON_COMPARE_SET_OC0_ON_TOP
    SET_OC0_ON_COMPARE_CLEAR_OC0_ON_TOP
*/
#define TIMER_0_PWM_COMPARE_OUTPUT_MODE OC0_DISCONNECTED_FPWM

/*
Phase_Correct Mode:

    OC0_DISCONNECTED_PCORRECT
    RESERVED_TIMER0_PCORRECT
    CLEAR_OC0_ON_COMPARE_UPCOUNTING_SET_OC0_ON_TOP_DOWNCOUNTING
    SET_OC0_ON_COMPARE_UPCOUNTING_CLEAR_OC0_ON_TOP_DOWNCOUNTING
*/
#define TIMER_0_PHASE_CORRECT_COMPARE_OUTPUT_MODE OC0_DISCONNECTED_PCORRECT

/*_______________________________________________________________**********************************_______________________________________________________________________*/
/* Timer_1 */

/* Set Timer_1 Compare Match Value A & B */

#define TIMER_1_COMPARE_MATCH_VALUE_A 0
#define TIMER_1_COMPARE_MATCH_VALUE_B 0

/* Set Timer_1 PreLoad Value */
#define TIMER_1_PRELOAD_VALUE 0

/* Set ICR1 Value */
#define TIMER_1_ICR1_VALUE 0

/*
ENABLE_TIMER_1_INTERRUPT_COMPAREMATCH_A
DISABLE_TIMER_1_INTERRUPT_COMPAREMATCH_A
*/
#define TIMER_1_INTERRUPT_COMPAREMATCH_A_STATUS DISABLE_TIMER_1_INTERRUPT_COMPAREMATCH_A

/*
ENABLE_TIMER_1_INTERRUPT_COMPAREMATCH_B
DISABLE_TIMER_1_INTERRUPT_COMPAREMATCH_B
*/
#define TIMER_1_INTERRUPT_COMPAREMATCH_B_STATUS DISABLE_TIMER_1_INTERRUPT_COMPAREMATCH_B

/*
ENABLE_TIMER_1_OVERFLOW_INTERRUPT
DISABLE_TIMER_1_OVERFLOW_INTERRUPT
*/
#define TIMER_1_INTERRUPT_OVERFLOW_STATUS ENABLE_TIMER_1_OVERFLOW_INTERRUPT

/*
ENABLE_TIMER_1_INPUTCAPTURE_INTERRUPT
DISABLE_TIMER_1_INPUTCAPTURE_INTERRUPT
*/
#define TIMER_1_INTERRUPT_INPUTCAPTURE_STATUS ENABLE_TIMER_1_INPUTCAPTURE_INTERRUPT

/*
TIMER_1_INPUTCAPTURE_RISINGEDGE
TIMER_1_INPUTCAPTURE_FALLINGEDGE
*/
#define TIMER_1_INPUTCAPTURE_TRIGGER TIMER_1_INPUTCAPTURE_RISINGEDGE

/*
ENABLE_TIMER_1_INPUTCAPTURE_NOISECANCELLER
DISABLE_TIMER_1_INPUTCAPTURE_NOISECANCELLER
 */
#define TIMER_1_INPUTCAPTURE_NOISECANCELLER_STATUS DISABLE_TIMER_1_INPUTCAPTURE_NOISECANCELLER

/*
Timer_1_Modes:

    TIMER_1_NORMAL_MODE
    TIMER_1_PWM_PHASE_CORRECT_8_BIT_MODE
    TIMER_1_PWM_PHASE_CORRECT_9_BIT_MODE
    TIMER_1_PWM_PHASE_CORRECT_10_BIT_MODE
    TIMER_1_CTC_OCR1A_MODE
    TIMER_1_FAST_PWM_8_BIT_MODE
    TIMER_1_FAST_PWM_9_BIT_MODE
    TIMER_1_FAST_PWM_10_BIT_MODE
    TIMER_1_PWM_PHASE_AND_FREQUENCY_CORRECT_ICR1_MODE
    TIMER_1_PWM_PHASE_AND_FREQUENCY_CORRECT_OCR1A_MODE
    TIMER_1_PWM_PHASE_CORRECT_ICR1_MODE
    TIMER_1_PWM_PHASE_CORRECT_OCR1A_MODE
    TIMER_1_CTC_ICR1_MODE
    TIMER_1_FAST_PWM_ICR1_MODE
    TIMER_1_FAST_PWM_OCR1A_MODE

 */
#define TIMER_1_MODE TIMER_1_NORMAL_MODE

/*
COMPARE_OUTPUT_MODE_TIMER_1_NON_PWM:

    OC1A_OC1B_DISCONNECTED_NONPWM
    TOGGLE_OC1A_OC1B_ON_COMPARE_NONPWM
    CLEAR_OC1_ON_COMPARE
    SET_OC1_ON_COMPARE

*/
#define TIMER_1_NON_PWM_COMPARE_OUTPUT_MODE_A OC1A_OC1B_DISCONNECTED_NONPWM
#define TIMER_1_NON_PWM_COMPARE_OUTPUT_MODE_B OC1A_OC1B_DISCONNECTED_NONPWM

/*
COMPARE_OUTPUT_MODE_TIMER_1_FAST_PWM:

    OC1A_OC1B_DISCONNECTED_FPWM
    TOGGLE_OC1A_OC1B_ON_COMPARE_FPWM
    CLEAR_OC1_ON_COMPARE_SET_OC1_ON_TOP
    SET_OC1_ON_COMPARE_CLEAR_OC1_ON_TOP


*/
#define TIMER_1_PWM_COMPARE_OUTPUT_MODE_A OC1A_OC1B_DISCONNECTED_FPWM
#define TIMER_1_PWM_COMPARE_OUTPUT_MODE_B OC1A_OC1B_DISCONNECTED_FPWM

/*
COMPARE_OUTPUT_MODE_TIMER_1_PHASE_CORRECT:

    OC1A_OC1B_DISCONNECTED_PCORRECT
    TOGGLE_OCA1_OCB1_ON_COMPARE_PCORRECT
    CLEAR_OC1_ON_COMPARE_UPCOUNTING_SET_OC1_ON_TOP_DOWNCOUNTING
    SET_OC1_ON_COMPARE_UPCOUNTING_CLEAR_OC1_ON_TOP_DOWNCOUNTING

*/

#define TIMER_1_PHASE_CORRECT_COMPARE_OUTPUT_MODE_A OC1A_OC1B_DISCONNECTED_PCORRECT
#define TIMER_1_PHASE_CORRECT_COMPARE_OUTPUT_MODE_B OC1A_OC1B_DISCONNECTED_PCORRECT

/*
TIMER_1_PRE_SCALAR_VALUE:

    PRE_SCALAR_VALUE_NO_CLOCK,
    PRE_SCALAR_VALUE_NONE,
    PRE_SCALAR_VALUE_8,
    PRE_SCALAR_VALUE_64,
    PRE_SCALAR_VALUE_256,
    PRE_SCALAR_VALUE_1024,
    EXTERNAL_CLOCK_ON_T_BIN_FALLINGEDGE,
    EXTERNAL_CLOCK_ON_T_BIN_RISINGEDGE

*/

#define TIMER_1_PRE_SCALAR_VALUE PRE_SCALAR_VALUE_8

/*************************************** Timer_2 ****************************************** */

/*
TIMER_2_MODES:
For Normal Mode --> TIMER_2_NORMAL_MODE
For PHASE_CORRECT Mode --> TIMER_2_PWM_PHASE_CORRECT_MODE
For CTC Mode --> TIMER_2_CTC_MODE
For FAST_PWM Mode --> TIMER_2_FAST_PWM_MODE
*/
#define TIMER_2_MODE TIMER_2_NORMAL_MODE

/* Set Timer_2 Compare Match Value */
#define TIMER_2_COMPARE_MATCH_VALUE 0

/* Set Timer_2 PreLoad Value */
#define TIMER_2_PRELOAD_VALUE 0

/*
ENABLE_TIMER_2_COMPAREMATCH_INTERRUPT
DISABLE_TIMER_2_COMPAREMATCH_INTERRUPT
*/
#define TIMER_2_COMPAREMATCH_INTERRUPT_STATUS DISABLE_TIMER_2_COMPAREMATCH_INTERRUPT

/*
ENABLE_TIMER_2_OVERFLOW_INTERRUPT
DISABLE_TIMER_2_OVERFLOW_INTERRUPT
*/
#define TIMER_2_OVERFLOW_INTERRUPT_STATUS ENABLE_TIMER_2_OVERFLOW_INTERRUPT

/*
Non_PWM Modes (CTC,NORMAL):

    OC2_DISCONNECTED_NONPWM
    TOGGLE_OC2_ON_COMPARE
    CLEAR_OC2_ON_COMPARE
    SET_OC2_ON_COMPARE
*/
#define TIMER_2_NON_PWM_COMPARE_OUTPUT_MODE OC2_DISCONNECTED_NONPWM

/*
FAST_PWM Mode:

    OC2_DISCONNECTED_FPWM
    RESERVED_TIMER2_FPWM
    CLEAR_OC2_ON_COMPARE_SET_OC2_ON_TOP
    SET_OC2_ON_COMPARE_CLEAR_OC2_ON_TOP
*/
#define TIMER_2_PWM_COMPARE_OUTPUT_MODE OC2_DISCONNECTED_FPWM

/*
Phase_Correct Mode:

    OC2_DISCONNECTED_PCORRECT
    RESERVED_TIMER2_PCORRECT
    CLEAR_OC2_ON_COMPARE_UPCOUNTING_SET_OC2_ON_TOP_DOWNCOUNTING
    SET_OC2_ON_COMPARE_UPCOUNTING_CLEAR_OC2_ON_TOP_DOWNCOUNTING
*/
#define TIMER_2_PHASE_CORRECT_COMPARE_OUTPUT_MODE OC2_DISCONNECTED_PCORRECT

/*
TIMER_2_PRE_SCALAR_VALUE:

    PRE_SCALAR_VALUE_NO_CLOCK,
    PRE_SCALAR_VALUE_NONE,
    PRE_SCALAR_VALUE_8,
    PRE_SCALAR_VALUE_64,
    PRE_SCALAR_VALUE_256,
    PRE_SCALAR_VALUE_1024,
    EXTERNAL_CLOCK_ON_T_BIN_FALLINGEDGE,
    EXTERNAL_CLOCK_ON_T_BIN_RISINGEDGE

*/
#define TIMER_2_PRE_SCALAR_VALUE PRE_SCALAR_VALUE_8

/*  WatchDog Timer */

#endif
