#ifndef TIMER_PRIVATE_H
#define TIMER_PRIVATE_H

#define TIFR *((volatile u8 *)0x58)
#define TIMSK *((volatile u8 *)0x59)

enum DIVFACTOR_TIMER
{
    PRE_SCALAR_VALUE_NO_CLOCK,
    PRE_SCALAR_VALUE_NONE,
    PRE_SCALAR_VALUE_8,
    PRE_SCALAR_VALUE_64,
    PRE_SCALAR_VALUE_256,
    PRE_SCALAR_VALUE_1024,
    EXTERNAL_CLOCK_ON_T_BIN_FALLINGEDGE,
    EXTERNAL_CLOCK_ON_T_BIN_RISINGEDGE
} DIVFACTOR_TIMER;

/* Timer 0 */
#define TIMER_0_NORMAL_MODE_SET 0b00000000
#define TIMER_0_PWM_PHASE_CORRECT_MODE_SET 0b01000000
#define TIMER_0_CTC_MODE_SET 0b00001000
#define TIMER_0_FAST_PWM_MODE_SET 0b01001000
#define TIMER_0_CLEAR_MODE 0b10000000

#define TIMER_0_NORMAL_MODE 1
#define TIMER_0_PWM_PHASE_CORRECT_MODE 2
#define TIMER_0_CTC_MODE 3
#define TIMER_0_FAST_PWM_MODE 4

#define ENABLE_TIMER_0_COMPAREMATCH_INTERRUPT 1
#define DISABLE_TIMER_0_COMPAREMATCH_INTERRUPT 0

#define ENABLE_TIMER_0_OVERFLOW_INTERRUPT 1
#define DISABLE_TIMER_0_OVERFLOW_INTERRUPT 0

enum COMPARE_OUTPUT_MODE_TIMER_0_NON_PWM
{
    OC0_DISCONNECTED_NONPWM,
    TOGGLE_OC0_ON_COMPARE,
    CLEAR_OC0_ON_COMPARE,
    SET_OC0_ON_COMPARE
} COMPARE_OUTPUT_MODE_TIMER_0_NON_PWM;

enum COMPARE_OUTPUT_MODE_TIMER_0_FAST_PWM
{
    OC0_DISCONNECTED_FPWM,
    RESERVED_TIMER0_FPWM,
    CLEAR_OC0_ON_COMPARE_SET_OC0_ON_TOP,
    SET_OC0_ON_COMPARE_CLEAR_OC0_ON_TOP
} COMPARE_OUTPUT_MODE_TIMER_0_FAST_PWM;

enum COMPARE_OUTPUT_MODE_TIMER_0_PHASE_CORRECT
{
    OC0_DISCONNECTED_PCORRECT,
    RESERVED_TIMER0_PCORRECT,
    CLEAR_OC0_ON_COMPARE_UPCOUNTING_SET_OC0_ON_TOP_DOWNCOUNTING,
    SET_OC0_ON_COMPARE_UPCOUNTING_CLEAR_OC0_ON_TOP_DOWNCOUNTING,
} COMPARE_OUTPUT_MODE_TIMER_0_PHASE_CORRECT;

#define TCCR0 *((volatile u8 *)0x53)
#define TCNT0 *((volatile u8 *)0x52)
#define OCR0 *((volatile u8 *)0x5c)

#define TCCR0_CS00 Pin_0
#define TCCR0_CS01 Pin_1
#define TCCR0_CS02 Pin_2
#define TCCR0_WGM01 Pin_3
#define TCCR0_COM00 Pin_4
#define TCCR0_COM01 Pin_5
#define TCCR0_WGM00 Pin_6
#define TCCR0_FOC0 Pin_7

#define TIFR_0CF0 Pin_1
#define TIFR_TOV0 Pin_0

#define TIMSK_OCIE0 Pin_1
#define TIMSK_TOIE0 Pin_0

/* Timer_1 */
#define TIMER_1_CLEAR_TCCR1A 0b00001100
#define TIMER_1_CLEAR_TCCR1B 0b11100000
#define TIMER_1_CLEAR_WAVEGEN_FIRST_THREE 0b11111000
#define TIMER_1_CLEAR_WAVEGEN_LEFT_TWO 0b00000011

#define ENABLE_TIMER_1_INTERRUPT_COMPAREMATCH_A 1
#define DISABLE_TIMER_1_INTERRUPT_COMPAREMATCH_A 0

#define ENABLE_TIMER_1_INTERRUPT_COMPAREMATCH_B 1
#define DISABLE_TIMER_1_INTERRUPT_COMPAREMATCH_B 0

#define ENABLE_TIMER_1_OVERFLOW_INTERRUPT 1
#define DISABLE_TIMER_1_OVERFLOW_INTERRUPT 0

#define ENABLE_TIMER_1_INPUTCAPTURE_NOISECANCELLER 1
#define DISABLE_TIMER_1_INPUTCAPTURE_NOISECANCELLER 0

#define ENABLE_TIMER_1_INPUTCAPTURE_INTERRUPT 1
#define DISABLE_TIMER_1_INPUTCAPTURE_INTERRUPT 0

#define TIMER_1_NORMAL_MODE 0
#define TIMER_1_PWM_PHASE_CORRECT_8_BIT_MODE 1
#define TIMER_1_PWM_PHASE_CORRECT_9_BIT_MODE 2
#define TIMER_1_PWM_PHASE_CORRECT_10_BIT_MODE 3
#define TIMER_1_CTC_OCR1A_MODE 4
#define TIMER_1_FAST_PWM_8_BIT_MODE 5
#define TIMER_1_FAST_PWM_9_BIT_MODE 6
#define TIMER_1_FAST_PWM_10_BIT_MODE 7
#define TIMER_1_PWM_PHASE_AND_FREQUENCY_CORRECT_ICR1_MODE 8
#define TIMER_1_PWM_PHASE_AND_FREQUENCY_CORRECT_OCR1A_MODE 9
#define TIMER_1_PWM_PHASE_CORRECT_ICR1_MODE 10
#define TIMER_1_PWM_PHASE_CORRECT_OCR1A_MODE 11
#define TIMER_1_CTC_ICR1_MODE 12
#define TIMER_1_RESERVED_MODE 13
#define TIMER_1_FAST_PWM_ICR1_MODE 14
#define TIMER_1_FAST_PWM_OCR1A_MODE 15

enum COMPARE_OUTPUT_MODE_TIMER_1_NON_PWM
{
    OC1A_OC1B_DISCONNECTED_NONPWM,
    TOGGLE_OC1A_OC1B_ON_COMPARE_NONPWM,
    CLEAR_OC1_ON_COMPARE,
    SET_OC1_ON_COMPARE
} COMPARE_OUTPUT_MODE_TIMER_1_NON_PWM;

enum COMPARE_OUTPUT_MODE_TIMER_1_FAST_PWM
{
    OC1A_OC1B_DISCONNECTED_FPWM,
    TOGGLE_OC1A_OC1B_ON_COMPARE_FPWM,
    CLEAR_OC1_ON_COMPARE_SET_OC1_ON_TOP,
    SET_OC1_ON_COMPARE_CLEAR_OC1_ON_TOP
} COMPARE_OUTPUT_MODE_TIMER_1_FAST_PWM;

enum COMPARE_OUTPUT_MODE_TIMER_1_PHASE_CORRECT
{
    OC1A_OC1B_DISCONNECTED_PCORRECT,
    TOGGLE_OCA1_OCB1_ON_COMPARE_PCORRECT,
    CLEAR_OC1_ON_COMPARE_UPCOUNTING_SET_OC1_ON_TOP_DOWNCOUNTING,
    SET_OC1_ON_COMPARE_UPCOUNTING_CLEAR_OC1_ON_TOP_DOWNCOUNTING
} COMPARE_OUTPUT_MODE_TIMER_1_PHASE_CORRECT;

#define OCR1A *((volatile u16 *)0x4A)
#define OCR1B *((volatile u16 *)0x48)
#define ICR1 *((volatile u16 *)0x46)
#define TCNT1 *((volatile u16 *)0x4C)

#define TCCR1A *((volatile u8 *)0x4f)

#define TCCR1A_WGM10 Pin_0
#define TCCR1A_WGM11 Pin_1
#define TCCR1A_FOC1B Pin_2
#define TCCR1A_FOC1A Pin_3
#define TCCR1A_COM1B0 Pin_4
#define TCCR1A_COM1B1 Pin_5
#define TCCR1A_COM1A0 Pin_6
#define TCCR1A_COM1A1 Pin_7

#define TCCR1B *((volatile u8 *)0x4E)

#define TCCR1B_CS10 Pin_0
#define TCCR1B_CS11 Pin_1
#define TCCR1B_CS12 Pin_2
#define TCCR1B_WGM12 Pin_3
#define TCCR1B_WGM13 Pin_4
#define TCCR1B_ICES1 Pin_6
#define TCCR1B_ICNC1 Pin_7

#define TIMSK_TOIE1 Pin_2
#define TIMSK_OCIE1B Pin_3
#define TIMSK_OCIE1A Pin_4
#define TIMSK_TICIE1 Pin_5

#define TIFR_ICF1 Pin_5
#define TIFR_OCF1A Pin_4
#define TIFR_OCF1B Pin_3
#define TIFR_TOV1 Pin_2

/* ICU */

#define TIMSK_TICIE1 Pin_5
#define TIMSK_OCIE1A Pin_4
#define TIMSK_OCIE1B Pin_3
#define TIMSK_TOIE1 Pin_2

/* Timer 2 */

#define TIMER_2_NORMAL_MODE_SET 0b00000000
#define TIMER_2_PWM_PHASE_CORRECT_MODE_SET 0b01000000
#define TIMER_2_CTC_MODE_SET 0b00001000
#define TIMER_2_FAST_PWM_MODE_SET 0b01001000
#define TIMER_2_CLEAR_MODE 0b10000111

#define TIMER_2_NORMAL_MODE 1
#define TIMER_2_PWM_PHASE_CORRECT_MODE 2
#define TIMER_2_CTC_MODE 3
#define TIMER_2_FAST_PWM_MODE 4

#define ENABLE_TIMER_2_COMPAREMATCH_INTERRUPT 1
#define DISABLE_TIMER_2_COMPAREMATCH_INTERRUPT 0

#define ENABLE_TIMER_2_OVERFLOW_INTERRUPT 1
#define DISABLE_TIMER_2_OVERFLOW_INTERRUPT 0

enum COMPARE_OUTPUT_MODE_TIMER_2_NON_PWM
{
    OC2_DISCONNECTED_NONPWM,
    TOGGLE_OC2_ON_COMPARE,
    CLEAR_OC2_ON_COMPARE,
    SET_OC2_ON_COMPARE
} COMPARE_OUTPUT_MODE_TIMER_2_NON_PWM;

enum COMPARE_OUTPUT_MODE_TIMER_2_FAST_PWM
{
    OC2_DISCONNECTED_FPWM,
    RESERVED_TIMER2_FPWM,
    CLEAR_OC2_ON_COMPARE_SET_OC2_ON_TOP,
    SET_OC2_ON_COMPARE_CLEAR_OC2_ON_TOP
} COMPARE_OUTPUT_MODE_TIMER_2_FAST_PWM;

enum COMPARE_OUTPUT_MODE_TIMER_2_PHASE_CORRECT
{
    OC2_DISCONNECTED_PCORRECT,
    RESERVED_TIMER2_PCORRECT,
    CLEAR_OC2_ON_COMPARE_UPCOUNTING_SET_OC2_ON_TOP_DOWNCOUNTING,
    SET_OC2_ON_COMPARE_UPCOUNTING_CLEAR_OC2_ON_TOP_DOWNCOUNTING
} COMPARE_OUTPUT_MODE_TIMER_2_PHASE_CORRECT;

#define TCCR2 *((volatile u8 *)0x45)
#define TCNT2 *((volatile u8 *)0x44)
#define OCR2 *((volatile u8 *)0x43)

#define TCCR2_CS20 Pin_0
#define TCCR2_CS21 Pin_1
#define TCCR2_CS22 Pin_2
#define TCCR2_WGM21 Pin_3
#define TCCR2_COM20 Pin_4
#define TCCR2_COM21 Pin_5
#define TCCR2_WGM20 Pin_6
#define TCCR2_FOC2 Pin_7

#define TIMSK_TOIE2 Pin_6
#define TIMSK_OCIE2 Pin_7

#define TIFR_OCF2 Pin_7
#define TIFR_TOV2 Pin_6

/*  WatchDog Timer */
#define WDTCR *((volatile u8 *)0x41)
#define WDTCR_WDTOE 4
#define WDTCR_WDE 3
#define WDTCR_WDP2 2
#define WDTCR_WDP1 1
#define WDTCR_WDP0 0

#define CLEAR_WDTCR_PRESCALLER 0b11111000
#define SET_WDTCR_WDE_WDTOE 0b00011000
#define CLEAR_WDTCR 0b00000000
#endif
