#ifndef UART_CONFIG_H
#define UART_CONFIG_H

/*
OSCILLATOR_FREQUENCY_1000000
OSCILLATOR_FREQUENCY_1843200
OSCILLATOR_FREQUENCY_2000000
OSCILLATOR_FREQUENCY_3686400
OSCILLATOR_FREQUENCY_4000000
OSCILLATOR_FREQUENCY_7372800
OSCILLATOR_FREQUENCY_8000000
OSCILLATOR_FREQUENCY_11059200
OSCILLATOR_FREQUENCY_14745600
OSCILLATOR_FREQUENCY_16000000
OSCILLATOR_FREQUENCY_18432000
OSCILLATOR_FREQUENCY_20000000
*/
#define SYSTEM_OSCILLATOR_FREQUENCY OSCILLATOR_FREQUENCY_8000000

/*
BAUD_2400
BAUD_4800
BAUD_9600
BAUD_14400
BAUD_28800
BAUD_38400
BAUD_57600
BAUD_76800
BAUD_115200
BAUD_230400
BAUD_250000
BAUD_500000
BAUD_1000000
*/
#define USART_BAUD_RATE BAUD_9600

/*
    USART_DISABLE_PARITY
    USART_EVEN_PARITY
    USART_ODD_PARITY
*/
#define USART_PARITY_CHECK_MODE USART_DISABLE_PARITY

/*
    USART_ONE_STOP_BIT
    USART_TWO_STOP_BIT
*/
#define USART_STOP_BIT USART_ONE_STOP_BIT

/*
    USART_FIVE_BIT
    USART_SIX_BIT
    USART_SEVEN_BIT
    USART_EIGHT_BIT
    USART_NINE_BIT
*/
#define DATA_AMOUNT USART_EIGHT_BIT

/*
    USART_ENABLE_ASYNCHRONOUS
    USART_ENABLE_SYNCHRONOUS
*/
#define USART_MODE_SELECT USART_ENABLE_ASYNCHRONOUS

/*
    USART_DISABLE_DOUBLE_SPEED
    USART_ENABLE_DOUBLE_SPEED
*/
#define USART_DOUBLE_SPEED_MODE USART_ENABLE_DOUBLE_SPEED

/*
USART_DISABLE_MULTI_PROCESSOR_MODE
USART_ENABLE_MULTI_PROCESSOR_MODE
*/
#define USART_MULTI_PROCESSOR_MODE USART_DISABLE_MULTI_PROCESSOR_MODE

/*
USART_DISABLE_RX_COMPLETE_INTERRUPT
USART_ENABLE_RX_COMPLETE_INTERRUPT
*/
#define USART_RX_COMPLETE_INTERRUPT USART_DISABLE_RX_COMPLETE_INTERRUPT

/*
USART_DISABLE_TX_COMPLETE_INTERRUPT
USART_ENABLE_TX_COMPLETE_INTERRUPT
*/
#define USART_TX_COMPLETE_INTERRUPT USART_DISABLE_TX_COMPLETE_INTERRUPT

/*
USART_DISABLE_REGISTER_EMPTY_INTERRUPT
USART_ENABLE_REGISTER_EMPTY_INTERRUPT
*/
#define USART_REGISTER_EMPTY_INTERRUPT USART_DISABLE_REGISTER_EMPTY_INTERRUPT

/*
USART_DISABLE_RECEIVER
USART_ENABLE_RECEIVER
*/
#define USART_RECEIVER_STATUS USART_ENABLE_RECEIVER

/*
USART_DISABLE_TRANSMITTER
USART_ENABLE_TRANSMITTER
*/
#define USART_TRANSMITTER_STATUS USART_ENABLE_TRANSMITTER

/*
    USART_TRANSMITTED_DATA_CHANGED_IN_RISING
    USART_TRANSMITTED_DATA_CHANGED_IN_FALLING
*/
#define USART_CLOCK_POLARITY USART_TRANSMITTED_DATA_CHANGED_IN_RISING
#endif