#ifndef TIMER_PRIVATE_H
#define TIMER_PRIVATE_H

#define TIFR *((volatile u8 *)0x58)
#define TIMSK *((volatile u8 *)0x59)

enum DIVFACTOR_TIMER
{
    PRE_SCALAR_VALUE_NO_CLOCK,
    PRE_SCALAR_VALUE_NONE,
    PRE_SCALAR_VALUE_8,
    PRE_SCALAR_VALUE_64,
    PRE_SCALAR_VALUE_256,
    PRE_SCALAR_VALUE_1024,
    EXTERNAL_CLOCK_ON_T_BIN_FALLINGEDGE,
    EXTERNAL_CLOCK_ON_T_BIN_RISINGEDGE
} DIVFACTOR_TIMER;

/* Timer_1 */
#define TIMER_1_CLEAR_TCCR1A 0b00001100
#define TIMER_1_CLEAR_TCCR1B 0b11100000
#define TIMER_1_CLEAR_WAVEGEN_FIRST_THREE 0b11111000
#define TIMER_1_SET_WAVEGEN_LAST_TWO 0b00000011
#define ENABLE_TIMER_1_INTERUPT_COMPAREMATCH_A 1
#define DISABLE_TIMER_1_INTERUPT_COMPAREMATCH_A 0
#define ENABLE_TIMER_1_INTERUPT_COMPAREMATCH_B 1
#define DISABLE_TIMER_1_INTERUP_COMPAREMATCH_B 0
#define ENABLE_TIMER_1_OVERFLOW_INTERUPT 1
#define DISABLE_TIMER_1_OVERFLOW_INTERUPT 0

#define TIMER_1_PWM_PHASE_CORRECT_ICR1_MODE 10

enum COMPARE_OUTPUT_MODE_TIMER_1_NON_PWM
{
    OC1A_OC1B_DISCONNECTED_NONPWM,
    TOGGLE_OC1A_OC1B_ON_COMPARE_NONPWM,
    CLEAR_OC1_ON_COMPARE,
    SET_OC1_ON_COMPARE
} COMPARE_OUTPUT_MODE_TIMER_1_NON_PWM;

enum COMPARE_OUTPUT_MODE_TIMER_1_FAST_PWM
{
    OC1A_OC1B_DISCONNECTED_FPWM,
    TOGGLE_OC1A_OC1B_ON_COMPARE_FPWM,
    CLEAR_OC1_ON_COMPARE_SET_OC1_ON_TOP,
    SET_OC1_ON_COMPARE_CLEAR_OC1_ON_TOP
} COMPARE_OUTPUT_MODE_TIMER_1_FAST_PWM;

enum COMPARE_OUTPUT_MODE_TIMER_1_PHASE_CORRECT
{
    OC1A_OC1B_DISCONNECTED_PCORRECT,
    TOGGLE_OCA1_OCB1_ON_COMPARE_PCORRECT,
    CLEAR_OC1_ON_COMPARE_UPCOUNTING_SET_OC1_ON_TOP_DOWNCOUNTING,
    SET_OC1_ON_COMPARE_UPCOUNTING_CLEAR_OC1_ON_TOP_DOWNCOUNTING
} COMPARE_OUTPUT_MODE_TIMER_1_PHASE_CORRECT;

#define OCR1A *((volatile u16 *)0x4A)
#define OCR1B *((volatile u16 *)0x48)
#define ICR1 *((volatile u16 *)0x46)
#define TCNT1 *((volatile u16 *)0x4C)

#define TCCR1A *((volatile u8 *)0x4f)

#define TCCR1A_WGM10 Pin_0
#define TCCR1A_WGM11 Pin_1
#define TCCR1A_FOC1B Pin_2
#define TCCR1A_FOC1A Pin_3
#define TCCR1A_COM1B0 Pin_4
#define TCCR1A_COM1B1 Pin_5
#define TCCR1A_COM1A0 Pin_6
#define TCCR1A_COM1A1 Pin_7

#define TCCR1B *((volatile u8 *)0x4E)

#define TCCR1B_CS10 Pin_0
#define TCCR1B_CS11 Pin_1
#define TCCR1B_CS12 Pin_2
#define TCCR1B_WGM12 Pin_3`
#define TCCR1B_WGM13 Pin_4
#define TCCR1B_ICES1 Pin_6
#define TCCR1B_ICNC1 Pin_7

#define TIMSK_TOIE1 Pin_2
#define TIMSK_OCIE1B Pin_3
#define TIMSK_OCIE1A Pin_4
#define TIMSK_TICIE1 Pin_5


#endif
