#ifndef CLCD_PRIVATE_H
#define CLCD_PRIVATE_H

/* Commands */
#define CLCD_CLEAR_DISPLAY_COMMAND 0b00000001
#define CLCD_RETURN_HOME_COMMAND 0b00000010
#define CLCD_RETURN_HOME_COMMAND 0x02
#define CLCD_DISABLE_SHIFT_DISPLAY_MODE 0x06

/* CONFIGURATIONS */

#define CLCD_SEND_MODE_BIT 4

#define CLCD_FONT_BIT 2
#define CLCD_FONT_5_8 0
#define CLCD_FONT_5_11 1

#define CLCD_NUMBER_OF_LINES_BIT 3
#define CLCD_1_LINE_MODE 0
#define CLCD_2_LINE_MODE 1

#define CLCD_DISPLAY_STATUS_BIT 2
#define CLCD_ENABLE_DISPLAY 1
#define CLCD_DISABLE_DISPLAY 0

#define CLCD_CURSOR_STATUS_BIT 1
#define CLCD_ENABLE_CURSOR 1
#define CLCD_DISABLE_CURSOR 0

#define CLCD_CURSOR_BLINK_STATUS_BIT 0
#define CLCD_ENABLE_CURSOR_PLINK 1
#define CLCD_DISABLE_CURSOR_PLINK 0

#define CLCD_CURSOR_ACTION_BIT 1
#define CLCD_CURSOR_INCREMENT 1
#define CLCD_CURSOR_DECREMENT 0

#define CLCD_DISPLAY_ACTION_BIT 0
#define CLCD_DISPLAY_SHIFT_RIGHT 1
#define CLCD_DISPLAY_SHIFT_RIGHT 0

/*INIT COMMANDS VALUE 8_BIT MODE*/
#define FUNCTION_SET_INIT 0b00100000
#define DISPLAY_ON_OFF_CONTROL_INIT 0b00001000
#define ENTRY_MODE_SET_INIT 0b00000110
#define SET_DDRAM_ADDRESS_INIT 0b10000000
#define SET_CGRAM_ADDRESS_INIT 0b01000000
/*INIT COMMANDS VALUE 4_BIT MODE*/

/* RAM */
#define CLCD_START_ADDRESS_FIRST_ROW 0x00
#define CLCD_START_ADDRESS_SECOND_ROW 0x40
#define CLCD_START_ADDRESS_THIRD_ROW 0X14
#define CLCD_START_ADDRESS_FOURTH_ROW 0X54
#define CLCD_FIRST_ROW 0
#define CLCD_FIRST_COLUMN 0

#endif
