#ifndef GLCD_PRIVATE_H
#define GLCD_PRIVATE_H

/* Commands */

#define GLCD_DISPLAY_ON_COMMAND 0b00111111
#define GLCD_DISPLAY_OFF_COMMAND 0b00111110
#define GLCD_CLEAR_DISPLAY_COMMAND 0xC0
#define GLCD_SET_MAXIMUM_CONTRAST_COMMAND 0xFF
#define GLCD_SET_CONTRAST_CONTROL_COMMAND 0x81
#define GLCD_POWER_ON_AND_SET_INTERNAL_VOLTAGE_COMMAND 0x2F
#define GLCD_SET_COMMON_DIRECTION_COMMAND 0xC8
#define GLCD_SET_SEGMENT_DIRECTION_COMMAND 0xA0
#define GLCD_SET_BIAS_VOLTAGE_COMMAND 0xA2
#define GLCD_READ_DISPLAY_DATA
#define GLCD_SET_Y_ADDRESS 0b01000000
#define GLCD_SET_X_ADDRESS 0b10111000
#define GLCD_SET_Z_ADDRESS 0b11000000
#define GLCD_FONT5x7 5
#define GLCD_FONT7x7 7
#define GLCD_M2_OFFSET 64
#define GLCD_START_PAGE 0
#define GLCD_START_Y 0

#endif
