#ifndef SPI_CONFIG_H
#define SPI_CONFIG_H

/*
ENABLE_SPI_INTERRUPT
DISABLE_SPI_INTERRUPT
*/
#define SPI_INTERRUPT_STATUS DISABLE_SPI_INTERRUPT

/*
DATA_ORDER_LSB_FIRST
DATA_ORDER_MSB_FIRST
*/
#define DATA_ORDER_TRANSMIT_FIRST DATA_ORDER_LSB_FIRST

/*
SPI_MASTER_MODE
SPI_SLAVE_MODE
*/
#define SPI_MODE_SELECT SPI_MASTER_MODE

/*
CLOCK_POLARITY_IDLE_HIGH
CLOCK_POLARITY_IDLE_LOW
*/
#define CLOCK_POLARITY_IDLE_STATUS CLOCK_POLARITY_IDLE_HIGH

/*
CLOCK_PHASE_SAMPLE_ON_LEADING
CLOCK_PHASE_SETUP_ON_LEADING
*/
#define CLOCK_PHASE_LEADING_ACTION CLOCK_PHASE_SETUP_ON_LEADING

/*
    PRE_SCALAR_VALUE_4
    PRE_SCALAR_VALUE_16
    PRE_SCALAR_VALUE_64
    PRE_SCALAR_VALUE_128
    PRE_SCALAR_VALUE_DOUBLE_SPEED_2
    PRE_SCALAR_VALUE_DOUBLE_SPEED_8
    PRE_SCALAR_VALUE_DOUBLE_SPEED_32
    PRE_SCALAR_VALUE_DOUBLE_SPEED_64
*/
#define MASTER_SPI_CLOCK_RATE PRE_SCALAR_VALUE_64

/*
ENABLE_SPI
DISABLE_SPI
*/
#define SPI_STATUS ENABLE_SPI

#endif