#ifndef SPI_PRIVATE_H
#define SPI_PRIVATE_H

#define SPI_CLEAR_SPCR_REGISTER 0b00000000
#define ENABLE_SPI_INTERRUPT 1
#define DISABLE_SPI_INTERRUPT 0
#define ENABLE_SPI 1
#define DISABLE_SPI 0
#define DATA_ORDER_LSB_FIRST 1
#define DATA_ORDER_MSB_FIRST 0
#define SPI_MASTER_MODE 1
#define SPI_SLAVE_MODE 0
#define CLOCK_POLARITY_IDLE_HIGH 1
#define CLOCK_POLARITY_IDLE_LOW 0
#define CLOCK_PHASE_SAMPLE_ON_LEADING 0
#define CLOCK_PHASE_SETUP_ON_LEADING 1
#define SPI_TIMEOUT_RECEIVE 22222
enum MASTER_SPI_CLOCK
{
    PRE_SCALAR_VALUE_4,
    PRE_SCALAR_VALUE_16,
    PRE_SCALAR_VALUE_64,
    PRE_SCALAR_VALUE_128,
    PRE_SCALAR_VALUE_DOUBLE_SPEED_2,
    PRE_SCALAR_VALUE_DOUBLE_SPEED_8,
    PRE_SCALAR_VALUE_DOUBLE_SPEED_32,
    PRE_SCALAR_VALUE_DOUBLE_SPEED_64
} MASTER_SPI_CLOCK;

#define SPCR *((volatile u8 *)0x2D)
#define SPCR_SPIE 7
#define SPCR_SPE 6
#define SPCR_DORD 5
#define SPCR_MSTR 4
#define SPCR_CPOL 3
#define SPCR_CPHA 2
#define SPCR_SPR1 1
#define SPCR_SPR0 0

#define SPSR *((volatile u8 *)0x2E)
#define SPSR_SPIF 7
#define SPSR_WCOL 6
#define SPSR_SPI2X 0

#define SPDR *((volatile u8 *)0x2F)

#endif
