#include "STD_Types.h"
#include "BIT_MATH.h"
#include "EXTI_private.h"
#include "EXTI_config.h"
#include "EXTI_init.h"

void (*EXTI_pvInt0Func)(void) = NULL;
void (*EXTI_pvInt1Func)(void) = NULL;
void (*EXTI_pvInt2Func)(void) = NULL;

u8 EXTI_VidEnableInterrupt(u8 Copy_u8Interrupt, u8 copy_u8Sense)
{
  u8 Local_u8ErrorStatus = OK;

#if Copy_u8Interrupt == INTERRUPT_0
#if INTERRUPT_SOURCE_0_SENSE_CONTROL == FALLING_EDGE
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC00);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC01);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == RISING_EDGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC00);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC01);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == LOW_LEVEL
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC00);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC01);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == ON_CHANGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC00);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC01);

#else
  u8 Local_u8ErrorStatus = NOK;

#endif
  SET_BIT(EXTI_GICR, GICR_INTERRUPT_0);

#elif Copy_u8Interrupt == INTERRUPT_1
#if INTERRUPT_SOURCE_0_SENSE_CONTROL == FALLING_EDGE
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC10);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC11);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == RISING_EDGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC10);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC11);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == LOW_LEVEL
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC10);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC11);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == ON_CHANGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC10);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC11);

#else
  u8 Local_u8ErrorStatus = NOK;

#endif
  SET_BIT(EXTI_GICR, GICR_INTERRUPT_1);

#elif Copy_u8Interrupt == INTERRUPT_2

#if INTERRUPT_SOURCE_0_SENSE_CONTROL == FALLING_EDGE
  CLEAR_BIT(EXTI_MCUSCR, MCUSCR_ISC2);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == RISING_EDGE
  SET_BIT(EXTI_MCUSCR, MCUSCR_ISC2);

#elif
  u8 Local_u8ErrorStatus = NOK;

#endif

  SET_BIT(EXTI_GICR, GICR_INTERRUPT_2);

#else
  u8 Local_u8ErrorStatus = NOK;

#endif

  return Local_u8ErrorStatus;
}

u8 EXTI_VidDisableInterrupt(u8 Copy_u8Interrupt)
{
  u8 Local_u8ErrorStatus = OK;
#if Copy_u8Interrupt == INTERRUPT_0
  Clear_BIT(EXTI_GICR, GICR_INTERRUPT_0);

#elif Copy_u8Interrupt == INTERRUPT_1
  Clear_BIT(EXTI_GICR, GICR_INTERRUPT_1);

#elif Copy_u8Interrupt == INTERRUPT_2
  Clear_BIT(EXTI_GICR, GICR_INTERRUPT_2);
#else
  Local_u8ErrorStatus = NOK;
#endif
  return Local_u8ErrorStatus;
}

void EXTI_VidEnable(void)
{
#if INTERRUPT_SOURCE_0 == INTERRUPT_0

#if INTERRUPT_SOURCE_0_SENSE_CONTROL == FALLING_EDGE
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC00);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC01);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == RISING_EDGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC00);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC01);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == LOW_LEVEL
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC00);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC01);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == ON_CHANGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC00);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC01);

#endif
  SET_BIT(EXTI_GICR, GICR_INTERRUPT_0);

#elif INTERRUPT_SOURCE_0 == INTERRUPT_1

#if INTERRUPT_SOURCE_0_SENSE_CONTROL == FALLING_EDGE
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC10);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC11);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == RISING_EDGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC10);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC11);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == LOW_LEVEL
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC10);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC11);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == ON_CHANGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC10);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC11);

#endif
  SET_BIT(EXTI_GICR, GICR_INTERRUPT_1);

#elif INTERRUPT_SOURCE_0 == INTERRUPT_2
#if INTERRUPT_SOURCE_0_SENSE_CONTROL == FALLING_EDGE
  CLEAR_BIT(EXTI_MCUSCR, MCUSCR_ISC2);

#elif INTERRUPT_SOURCE_0_SENSE_CONTROL == RISING_EDGE
  SET_BIT(EXTI_MCUSCR, MCUSCR_ISC2);

#endif
  SET_BIT(EXTI_GICR, GICR_INTERRUPT_2);

#endif

  /******************************************************************************************/

#if INTERRUPT_SOURCE_1 == INTERRUPT_0

#if INTERRUPT_SOURCE_1_SENSE_CONTROL == FALLING_EDGE
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC00);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC01);

#elif INTERRUPT_SOURCE_1_SENSE_CONTROL == RISING_EDGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC00);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC01);

#elif INTERRUPT_SOURCE_1_SENSE_CONTROL == LOW_LEVEL
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC00);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC01);

#elif INTERRUPT_SOURCE_1_SENSE_CONTROL == ON_CHANGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC00);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC01);

#endif
  SET_BIT(EXTI_GICR, GICR_INTERRUPT_0);

#elif INTERRUPT_SOURCE_1 == INTERRUPT_1

#if INTERRUPT_SOURCE_1_SENSE_CONTROL == FALLING_EDGE
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC10);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC11);

#elif INTERRUPT_SOURCE_1_SENSE_CONTROL == RISING_EDGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC10);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC11);

#elif INTERRUPT_SOURCE_1_SENSE_CONTROL == LOW_LEVEL
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC10);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC11);

#elif INTERRUPT_SOURCE_1_SENSE_CONTROL == ON_CHANGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC10);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC11);

#endif
  SET_BIT(EXTI_GICR, GICR_INTERRUPT_1);

#elif INTERRUPT_SOURCE_1 == INTERRUPT_2
#if INTERRUPT_SOURCE_1_SENSE_CONTROL == FALLING_EDGE
  CLEAR_BIT(EXTI_MCUSCR, MCUSCR_ISC2);

#elif INTERRUPT_SOURCE_1_SENSE_CONTROL == RISING_EDGE
  SET_BIT(EXTI_MCUSCR, MCUSCR_ISC2);

#endif
  SET_BIT(EXTI_GICR, GICR_INTERRUPT_2);

#endif

  /******************************************************************************************/

#if INTERRUPT_SOURCE_2 == INTERRUPT_0

#if INTERRUPT_SOURCE_2_SENSE_CONTROL == FALLING_EDGE
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC00);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC01);

#elif INTERRUPT_SOURCE_2_SENSE_CONTROL == RISING_EDGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC00);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC01);

#elif INTERRUPT_SOURCE_2_SENSE_CONTROL == LOW_LEVEL
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC00);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC01);

#elif INTERRUPT_SOURCE_2_SENSE_CONTROL == ON_CHANGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC00);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC01);

#endif
  SET_BIT(EXTI_GICR, GICR_INTERRUPT_0);

#elif INTERRUPT_SOURCE_2 == INTERRUPT_1

#if INTERRUPT_SOURCE_2_SENSE_CONTROL == FALLING_EDGE
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC10);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC11);

#elif INTERRUPT_SOURCE_2_SENSE_CONTROL == RISING_EDGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC10);
  SET_BIT(EXTI_MCUCR, MCUCR_ISC11);

#elif INTERRUPT_SOURCE_2_SENSE_CONTROL == LOW_LEVEL
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC10);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC11);

#elif INTERRUPT_SOURCE_2_SENSE_CONTROL == ON_CHANGE
  SET_BIT(EXTI_MCUCR, MCUCR_ISC10);
  CLEAR_BIT(EXTI_MCUCR, MCUCR_ISC11);

#endif
  SET_BIT(EXTI_GICR, GICR_INTERRUPT_1);

#elif INTERRUPT_SOURCE_2 == INTERRUPT_2
#if INTERRUPT_SOURCE_2_SENSE_CONTROL == FALLING_EDGE
  CLEAR_BIT(EXTI_MCUSCR, MCUSCR_ISC2);

#elif INTERRUPT_SOURCE_2_SENSE_CONTROL == RISING_EDGE
  SET_BIT(EXTI_MCUSCR, MCUSCR_ISC2);

#endif
  SET_BIT(EXTI_GICR, GICR_INTERRUPT_2);

#endif
}

void EXTI_VidDisable(void)
{
#if INTERRUPT_DISABLE_0 == DISABLE
  Clear_BIT(EXTI_GICR, GICR_INTERRUPT_0);
#endif

#if INTERRUPT_DISABLE_1 == DISABLE
  Clear_BIT(EXTI_GICR, GICR_INTERRUPT_1);
#endif

#if INTERRUPT_DISABLE_2 == DISABLE
  Clear_BIT(EXTI_GICR, GICR_INTERRUPT_2);
#endif
}

/* Global pointer to Function to hold The User ISR Address */

void (*EXTI_pvInt0Func)(void) = NULL;
u8 EXTI_u8Int0SetCallBack(void (*Copy_pvInt0Func)(void))
{
  u8 Local_u8ErrorStatus = OK;
  if (Copy_pvInt0Func != NULL)
  {
    EXTI_pvInt0Func = Copy_pvInt0Func;
  }
  else
  {
    Local_u8ErrorStatus = NULL_POINTER;
  }
  return Local_u8ErrorStatus;
}

void (*EXTI_pvInt1Func)(void) = NULL;
u8 EXTI_u8Int1SetCallBack(void (*Copy_pvInt1Func)(void))
{
  u8 Local_u8ErrorStatus = OK;
  if (Copy_pvInt1Func != NULL)
  {
    EXTI_pvIn1Func = Copy_pvInt1Func;
  }
  else
  {
    Local_u8ErrorStatus = NULL_POINTER;
  }
  return Local_u8ErrorStatus;
}

void (*EXTI_pvInt2Func)(void) = NULL;
u8 EXTI_u8Int2SetCallBack(void (*Copy_pvInt2Func)(void))
{
  u8 Local_u8ErrorStatus = OK;
  if (Copy_pvInt2Func != NULL)
  {
    EXTI_pvInt2Func = Copy_pvInt2Func;
  }
  else
  {
    Local_u8ErrorStatus = NULL_POINTER;
  }
  return Local_u8ErrorStatus;
}

/* ISR OF INT_0 */

void __vector_1(void) __attribute__((signal));
void __vector_1(void)
{
  if (EXTI_pvInt0Func != NULL)
  {
    EXTI_pvInt0Func();
  }
  else
  {
    /* Do Nothing */
  }
}

/* ISR OF INT_1 */

void __vector_2(void) __attribute__((signal));
void __vector_2(void)
{
  if (EXTI_pvInt1Func != NULL)
  {
    EXTI_pvInt1Func();
  }
  else
  {
    /* Do Nothing */
  }
}

/* ISR OF INT_2 */

void __vector_3(void) __attribute__((signal));
void __vector_3(void)
{
  if (EXTI_pvInt2Func != NULL)
  {
    EXTI_pvInt2Func();
  }
  else
  {
    /* Do Nothing */
  }
}
